version: "3.9"

networks:
  traefik-public:
    external: true

services:
  traefik:
    image: traefik:v2.6
    container_name: global_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/traefik/conf/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
